services:
  - type: web
    name: keep-alive-service
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
      - key: API_BASE_URL
        value: your-backend-url-here
      - key: KEEP_ALIVE_EMAIL
        value: your-email@example.com
      - key: KEEP_ALIVE_PASSWORD
        value: your-secure-password
      - key: KEEP_ALIVE_INTERVAL
        value: '720000'  # 12 minutes in milliseconds (override in .env for testing)
      - key: LOG_LEVEL
        value: 'info'
      - key: ALERT_EMAIL
        value: ''
      - key: SMTP_HOST
        value: ''
      - key: SMTP_PORT
        value: '587'
      - key: SMTP_USER
        value: ''
      - key: SMTP_PASS
        value: ''
      - key: SMTP_FROM
        value: ''
    plan: free
